language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jinwilliam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jinwilliam/react-test npm test

after_success:
  - docker build -t jinwilliam/multi-client ./client
  - docker build -t jinwilliam/multi-nginx ./nginx
  - docker build -t jinwilliam/multi-server ./server
  - docker build -t jinwilliam/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push these to docker hub
  - docker push jinwilliam/multi-client
  - docker push jinwilliam/multi-nginx
  - docker push jinwilliam/multi-server
  - docker push jinwilliam/multi-worker
